### PR TITLE
passport added and export issue fixed

### PR DESCRIPTION
**Pull request by tanay13**
Changes done as said regarding export and .ts

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
>  Parameter 'req' implicitly has an 'any' type.

just put a `:any` after the variable to fix this error.

> new LocalStrategy({ usernameField: 'email' }, (email, password, done) => {
change it to 
`new LocalStrategy({ usernameField: 'email' }, (email:string, password:string, done:any) => {`

Try this and let's see how many errors fix.

**Comment by tanay13** [comment]
@YashKumarVerma Okay i will do it

**Comment by tanay13** [comment]
@YashKumarVerma i should add :any to all the variable which are causing error right?

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma i should add :any to all the variable which are causing error right?

yes, any variable which throws an error saying "implicit.....", you can try string, or string[] etc depending on the data type

**Comment by tanay13** [comment]
@YashKumarVerma please recheck the code i have fixed it .

**Comment by YashKumarVerma** [comment]
Check travis errors

**Comment by tanay13** [comment]
@YashKumarVerma I am not sure how to fix the errors shown by travis

**Comment by YashKumarVerma** [comment]
Try searching them on gooogle, will the code if I get time in evening.

**Comment by YashKumarVerma** [comment]
try pulling latest chages from .travis.yml

**Pull request closed without merging**
