### PR TITLE
Deleted Docker Commands and file

### LINKED ISSUE #3: Remove docker commands from travis.yml
Delete the docker file as well

### PR DESCRIPTION
**Pull request by karankartikeya**
close #3

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
Add fixes #issue number to attach issue to this pr.

**Comment by karankartikeya** [comment]
> Add fixes #issue number to attach issue to this pr.


Do i have to resubmit a pr or i can link it through here also?
Please guide regarding linking through here if possible.

**Comment by YashKumarVerma** [comment]
> > Add fixes #issue number to attach issue to this pr.
> 
> Do i have to resubmit a pr or i can link it through here also?
> Please guide regarding linking through here if possible.

image
Check the edit button

**Comment by YashKumarVerma** [comment]
Thanks a lot for your contributions.

**Comment by karankartikeya** [comment]
> > > Add fixes #issue number to attach issue to this pr.
> > 
> > 
> > Do i have to resubmit a pr or i can link it through here also?
> > Please guide regarding linking through here if possible.
> 
> image
> Check the edit button

Thank you

**Pull request merged**
